#!/bin/bash

set -xuve

# HEADER

HPCROOTDIR=${1:-%HPCROOTDIR%}
EXPERIMENT_NAME=${2:-%AQUA.EXPERIMENT_NAME%}
# AQUA_LRA_OUTPUT_PATH added to sync the LRA results to a common place
LOCAL_LRA_OUTPUT_PATH=${3:-%AQUA.LOCAL_LRA_OUTPUT_PATH%}
CENTRAL_LRA_PATH=${4:-%AQUA.CENTRAL_LRA_OUTPUT_PATH%}
CATALOG=${5:-%HPCCATALOG_NAME%}
MODEL_UPPER=${6:-%REQUEST.MODEL_NAME_UPPER%}
PROJDEST=${7:-%PROJECT.PROJECT_DESTINATION%}
RESOLUTION=${8:-%MODEL.RESOLUTION%}

# END_HEADER

MODEL_AND_RES="${MODEL_UPPER}-${RESOLUTION}"
SOURCE_CATALOG="${HPCROOTDIR}/catalog/catalogs/${CATALOG}"/catalog/${MODEL_AND_RES}/${EXPERIMENT_NAME}.yaml

sed -i -e "s|${LOCAL_LRA_OUTPUT_PATH}|${CENTRAL_LRA_PATH}|g" "${SOURCE_CATALOG}"
