[pytest]
addopts =
    --verbose --ignore=regression
    --cov=lib --cov-config=pyproject.toml
    --cov-report=html:tests/bats_tests/htmlcov
    --cov-report=xml:tests/bats_tests/coverage.xml
    --cov-report=term
    --strict-markers
testpaths =
    tests/bats_tests/
    tests/unit/
collect_ignore_glob =
    wftools/*
doctest_optionflags =
    NORMALIZE_WHITESPACE
    IGNORE_EXCEPTION_DETAIL
    ELLIPSIS
