type: local
engine: toc
schema: "%REQUEST.FDB_HOME%/native/etc/fdb/schema"
spaces:
  - handler: Default
    roots:
      - path: "%REQUEST.FDB_HOME%/native"
        wipe: true
        archive: true
        list: true
        retrieve: true
